### PR TITLE
Improve how we re generate user permissions

### PR DESCRIPTION
**Pull request by franck-boullier**
# Improvement and bug fixes:

- User permission are added without truncating the `user_group_map` table anymore. See #88.
- Revoke user permission is done directly in the table `user_group_map`
- seeded user now have an email address @case.dev.unee-t.com instead of @mailinator.com. See #87.

### CODE REVIEW

**Comment by franck-boullier** [comment]
Implemented in DEV/Staging and in DEMO environment.
Waiting for test results from Uilicious before implementing in the PROD and merge to master.

**Comment by franck-boullier** [comment]
The upgraded BZ schema is implemented in the PROD now.
We need to add updated the snapshots of the Seed DB before we can merge this in the master.

**Comment by kaihendry** [comment]
I don't think Naor nor I have the skills to properly review this 15k sloc SQL patchset. So can it please just be merged so we can have a canonical schema starting point?

**Comment by franck-boullier** [comment]
> can it please just be merged so we can have a canonical schema starting point?

Unfortunately not yet because as mentioned in https://github.com/unee-t/bz-database/pull/89#issuecomment-433765474, We need to add updated the snapshots of the Seed DB before we can merge this in the master.

I'll try to do that tonight

**Comment by kaihendry** [comment]
I can see the message "Running invite_user_in_a_role_in_a_unit.sql with invite id xTSQQXiSioPmAPsNo with env 1" before the user_group_map table was truncated again.

https://media.dev.unee-t.com/2018-11-07/cloudwatch.mp4

**Pull request merged**
